name: jewelx
description: "سوق مجوهرات (جديد/مستعمل) مع 3D، ثيم وردي–خوخي مطابق للصورة، سلة وCheckout محلي، تواصل مع البائع، مقارنة، فلاتر، بحث شامل، Dark Mode، ولغتين AR/EN."
publish_to: 'none'
version: 5.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  iconly: ^1.0.1
  flutter_3d_controller: ^0.0.1
  flutter_animate: 4.5.2
  tutorial_coach_mark: ^1.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
